// Schema estrutural compartilhado entre a 1ª geração (api/analyze.ts) e a 2ª
// passada de verificação (api/analyze-verify.ts) — ambas produzem exatamente
// o mesmo formato de AvaliacaoResultado (ver src/lib/avaliacao-types.ts).

const fatorSchema = {
  type: 'OBJECT',
  properties: {
    fator: { type: 'STRING' },
    valor: { type: 'NUMBER' },
    origem: { type: 'STRING' },
    justificativa: { type: 'STRING' },
    campoAplicacao: { type: 'STRING' },
    abrangenciaRegional: { type: 'STRING' },
    abrangenciaTemporal: { type: 'STRING' },
  },
  required: ['fator', 'valor', 'origem', 'justificativa', 'campoAplicacao', 'abrangenciaRegional', 'abrangenciaTemporal'],
}

export const nbrResponseSchema = {
  type: 'OBJECT',
  properties: {
    tipoImovel: {
      type: 'STRING',
      enum: [
        'Terreno/lote urbano',
        'Casa residencial',
        'Apartamento',
        'Sobrado',
        'Imóvel comercial',
        'Sala/conjunto comercial',
        'Galpão',
        'Loja',
        'Prédio comercial',
        'Imóvel industrial',
        'Imóvel rural',
        'Empreendimento imobiliário',
        'Outros',
      ],
    },
    finalidade: { type: 'STRING', enum: ['Valor de mercado', 'Valor de garantia'] },
    caracterizacao: {
      type: 'OBJECT',
      properties: {
        padraoConstrutivo: { type: 'STRING' },
        estadoConservacao: { type: 'STRING' },
        patologias: { type: 'ARRAY', items: { type: 'STRING' } },
        descricaoEntorno: { type: 'STRING' },
        zoneamento: { type: 'STRING' },
      },
      required: ['padraoConstrutivo', 'estadoConservacao', 'patologias', 'descricaoEntorno', 'zoneamento'],
    },
    metodo: {
      type: 'OBJECT',
      properties: {
        metodo: { type: 'STRING' },
        justificativa: { type: 'STRING' },
      },
      required: ['metodo', 'justificativa'],
    },
    amostras: {
      type: 'ARRAY',
      items: {
        type: 'OBJECT',
        properties: {
          id: { type: 'STRING' },
          fonte: { type: 'STRING' },
          data: { type: 'STRING' },
          endereco: { type: 'STRING' },
          tipologia: { type: 'STRING' },
          areaM2: { type: 'NUMBER' },
          valorAnunciado: { type: 'NUMBER' },
          valorUnitario: { type: 'NUMBER' },
          dormitorios: { type: 'NUMBER' },
          suites: { type: 'NUMBER' },
          banheiros: { type: 'NUMBER' },
          vagas: { type: 'NUMBER' },
          padrao: { type: 'STRING' },
          conservacao: { type: 'STRING' },
          idadeAnos: { type: 'NUMBER' },
          distanciaM: { type: 'NUMBER' },
          evidencia: { type: 'STRING' },
          url: { type: 'STRING' },
          fatoresAplicados: { type: 'ARRAY', items: fatorSchema },
          valorUnitarioHomogeneizado: { type: 'NUMBER' },
        },
        required: [
          'id',
          'fonte',
          'data',
          'endereco',
          'tipologia',
          'areaM2',
          'valorAnunciado',
          'valorUnitario',
          'dormitorios',
          'suites',
          'banheiros',
          'vagas',
          'padrao',
          'conservacao',
          'idadeAnos',
          'distanciaM',
          'evidencia',
          'fatoresAplicados',
          'valorUnitarioHomogeneizado',
        ],
      },
    },
    tratamentoEstatistico: {
      type: 'OBJECT',
      properties: {
        media: { type: 'NUMBER' },
        mediana: { type: 'NUMBER' },
        minimo: { type: 'NUMBER' },
        maximo: { type: 'NUMBER' },
        coeficienteVariacao: { type: 'NUMBER' },
        amplitude: { type: 'NUMBER' },
        amostrasUtilizadas: { type: 'NUMBER' },
        amostrasExcluidas: {
          type: 'ARRAY',
          items: {
            type: 'OBJECT',
            properties: { id: { type: 'STRING' }, motivo: { type: 'STRING' } },
            required: ['id', 'motivo'],
          },
        },
      },
      required: ['media', 'mediana', 'minimo', 'maximo', 'coeficienteVariacao', 'amplitude', 'amostrasUtilizadas', 'amostrasExcluidas'],
    },
    parecer: {
      type: 'OBJECT',
      properties: {
        valorMercado: { type: 'NUMBER' },
        faixaMin: { type: 'NUMBER' },
        faixaMax: { type: 'NUMBER' },
        liquidez: { type: 'STRING', enum: ['Muito Alta', 'Alta', 'Normal', 'Baixa', 'Muito Baixa'] },
        fundamentacao: { type: 'STRING' },
      },
      required: ['valorMercado', 'faixaMin', 'faixaMax', 'liquidez', 'fundamentacao'],
    },
    grauFundamentacao: {
      type: 'OBJECT',
      properties: {
        itens: {
          type: 'ARRAY',
          items: {
            type: 'OBJECT',
            properties: {
              item: { type: 'STRING' },
              grauAtingido: { type: 'STRING', enum: ['I', 'II', 'III'] },
              descricao: { type: 'STRING' },
            },
            required: ['item', 'grauAtingido', 'descricao'],
          },
        },
        grauFinal: { type: 'STRING', enum: ['I', 'II', 'III'] },
        justificativa: { type: 'STRING' },
      },
      required: ['itens', 'grauFinal', 'justificativa'],
    },
    grauPrecisao: {
      type: 'OBJECT',
      properties: {
        estimativaPontual: { type: 'NUMBER' },
        limiteInferior: { type: 'NUMBER' },
        limiteSuperior: { type: 'NUMBER' },
        amplitude: { type: 'NUMBER' },
        grauFinal: { type: 'STRING', enum: ['I', 'II', 'III'] },
      },
      required: ['estimativaPontual', 'limiteInferior', 'limiteSuperior', 'amplitude', 'grauFinal'],
    },
    valorFinal: {
      type: 'OBJECT',
      properties: {
        valorUnitario: { type: 'NUMBER' },
        areaAvalianda: { type: 'NUMBER' },
        valorTotal: { type: 'NUMBER' },
        intervaloMin: { type: 'NUMBER' },
        intervaloMax: { type: 'NUMBER' },
        valorAdotado: { type: 'NUMBER' },
        justificativaAdocao: { type: 'STRING' },
      },
      required: ['valorUnitario', 'areaAvalianda', 'valorTotal', 'intervaloMin', 'intervaloMax', 'valorAdotado', 'justificativaAdocao'],
    },
    descricaoLaudo: { type: 'STRING' },
    dadosInsuficientes: { type: 'BOOLEAN' },
    dadosInsuficientesMotivo: { type: 'STRING' },
    documentosAnalisados: {
      type: 'ARRAY',
      items: {
        type: 'OBJECT',
        properties: {
          label: { type: 'STRING' },
          resumo: { type: 'STRING' },
        },
        required: ['label', 'resumo'],
      },
    },
    divergencias: {
      type: 'ARRAY',
      items: {
        type: 'OBJECT',
        properties: {
          campo: { type: 'STRING' },
          valorVistoria: { type: 'STRING' },
          valorDocumento: { type: 'STRING' },
          percentual: { type: 'NUMBER' },
          mensagem: { type: 'STRING' },
        },
        required: ['campo', 'valorVistoria', 'valorDocumento', 'percentual', 'mensagem'],
      },
    },
    financiabilidade: {
      type: 'OBJECT',
      properties: {
        status: { type: 'STRING', enum: ['Financiável', 'Financiável com restrições', 'Não financiável'] },
        motivos: { type: 'ARRAY', items: { type: 'STRING' } },
      },
      required: ['status', 'motivos'],
    },
    iqg: {
      type: 'OBJECT',
      properties: {
        score: { type: 'NUMBER' },
        classificacao: { type: 'STRING', enum: ['Premium', 'Atenção', 'Inadequada'] },
        fatores: {
          type: 'OBJECT',
          properties: {
            liquidez: { type: 'NUMBER' },
            conservacao: { type: 'NUMBER' },
            localizacao: { type: 'NUMBER' },
            riscoJuridico: { type: 'NUMBER' },
            riscoAmbiental: { type: 'NUMBER' },
            riscoDocumental: { type: 'NUMBER' },
          },
          required: ['liquidez', 'conservacao', 'localizacao', 'riscoJuridico', 'riscoAmbiental', 'riscoDocumental'],
        },
      },
      required: ['score', 'classificacao', 'fatores'],
    },
  },
  required: [
    'tipoImovel',
    'finalidade',
    'caracterizacao',
    'metodo',
    'amostras',
    'tratamentoEstatistico',
    'parecer',
    'grauFundamentacao',
    'grauPrecisao',
    'valorFinal',
    'descricaoLaudo',
    'dadosInsuficientes',
    'documentosAnalisados',
    'divergencias',
    'financiabilidade',
    'iqg',
  ],
}
